name: GitHubTodo
options:
  bundleIdPrefix: com.chrisnewsome
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.chrisnewsome.todoglass
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 0.1.0
    DEVELOPMENT_TEAM: ""
    INFOPLIST_FILE: TodoGlass/Info.plist
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    SWIFT_VERSION: 5.9
    ENABLE_PREVIEWS: YES
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
    TARGETED_DEVICE_FAMILY: 1
    SWIFT_STRICT_CONCURRENCY: COMPLETE
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    Release:
      SWIFT_COMPILATION_MODE: wholemodule

targets:
  GitHubTodo:
    type: application
    platform: iOS
    sources:
      - TodoGlass/Sources
    resources:
      - TodoGlass/Resources
    settings:
      base:
        PRODUCT_NAME: "GitHub Todo"
